### PR TITLE
Created Navbar_1

### PR DESCRIPTION
**Pull request by AnuragParashar2000**

### CODE REVIEW

**Comment by Ovenoboyo** [comment]
@AnuragParashar2000 there are a few changes we would like you to carry out before we merge this PR.

- Please use lowercase letters when naming directories or files
- Avoid special characters like _ and numbers when naming files
- Make use of props instead of hard-coded stuff (in your case it would be the navbar links and their titles)
- Instead of react-icons or any other icon library, make use of [slots](https://dev.to/hryggrbyr/using-slots-in-react-pcp)
- Please provide us with an example of your component implemented in [example](/Dezenix/frontend-reactjs/tree/main/example) folder

**Comment by Ovenoboyo** [comment]
Also your PR is failing our [CI build](https://github.com/Dezenix/frontend-reactjs/runs/4498189092?check_suite_focus=true)

**Review by Ovenoboyo — CHANGES_REQUESTED** [review]
Check previous comments for changes

**Comment by AnuragParashar2000** [comment]
ok, thank you very much for guiding me through this, I will surely
implement them.

**Pull request closed without merging**
